version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 200000000
      KAFKA_MAX_REQUEST_SIZE: 200000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - minio
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    
    
    entrypoint: ["/wait-for-it.sh", "kafka:9092", "--", "python", "app/main.py"]

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - GOOGLE_APPLICATION_CREDENTIALS=/app/consumer/servicekey.json
    entrypoint: [ "python", "-u", "consumer.py"]
    volumes:
      - ./consumer/servicekey.json:/app/consumer/servicekey.json
    restart: always

  crawled-data-consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - minio
    environment:
      - KAFKA_BROKER=kafka:9092
      - GOOGLE_APPLICATION_CREDENTIALS=/app/servicekey.json
    entrypoint: [ "python", "-u", "crawled_data_consumer.py"]
    volumes:
      - ./consumer/servicekey.json:/app/servicekey.json
      
    restart: always
  

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_X_FRAME_OPTIONS=
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    
  airflow:
    build:
      context: ./dags     # Pointing to the 'dags' folder where the Dockerfile is located
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6380/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/servicekey.json
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags  # Mount the 'dags' folder to Airflow's DAGs directory
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./servicekey.json:/opt/airflow/servicekey.json

    command: >
      bash -c " airflow db init && airflow db upgrade &&
              airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow webserver"
    restart: always
    depends_on:
      - kafka
      - minio
      - postgres

  airflow-scheduler:
    build:
      context: ./dags    # Ensure the scheduler uses the same custom image
    depends_on:
      - airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6380/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/servicekey.json
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: >
      bash -c " airflow db init && airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
              airflow scheduler"
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./servicekey.json:/opt/airflow/servicekey.json
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server --bind 0.0.0.0 --port 6380
    ports:
      - "6380:6379"
  airflow-worker:
    build:
      context: ./dags
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6380/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
    command: >
      airflow celery worker
    depends_on:
      - airflow
      - redis
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./servicekey.json:/opt/airflow/servicekey.json
      
      
    restart: always


volumes:
  grafana_data:
    driver: local
  postgres_data:
    driver: local
