{
 "title": "BDE Mini Project",
 "time": { "from": "2020-01-01T00:00:00.000Z", "to": "2024-09-28T00:00:00.000Z" },
 "panels": [
  {
   "title": "Incident Location",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "bdeminiproject",
     "project": "project_id",
     "rawSql": "SELECT Lat, Lon FROM project_id.bdeminiproject.master LIMIT 5000\n"
    }
   ]
  },
  {
   "title": "Time of the Day Occurences",
   "type": "trend",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "project": "project_id",
     "rawSql": "SELECT \r\n  EXTRACT(HOUR FROM TIME(`Time Occ`)) AS time,\r\n  COUNT(*) AS occurrence_count\r\nFROM \r\n  `project_id.bdeminiproject.master`\r\nGROUP BY \r\n  time\r\nORDER BY \r\n  time;\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "bdeminiproject",
     "project": "project_id",
     "rawSql": "SELECT \n  CAST(`Date Occ` AS TIMESTAMP) AS time,\n  COUNT(*) AS occurrence_count\nFROM \n  `project_id.bdeminiproject.master`\nGROUP BY \n  time\nORDER BY \n  time;\n"
    }
   ]
  },
  {
   "title": "Number of Entries",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "project_id",
     "rawSql": "SELECT \r\n  Count(*)\r\nFROM \r\n  `project_id.bdeminiproject.master`\r\n;\r\n"
    }
   ]
  },
  {
   "title": "Victim Demographics by Age and Sex",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "bdeminiproject",
     "project": "project_id",
     "rawSql": "SELECT \n  `Vict Age`, \n  `Vict Sex`, \n  COUNT(*) AS `Victim Count`\nFROM \n  `project_id.bdeminiproject.master`\nWHERE \n  `Vict Age` IS NOT NULL \n  AND `Vict Age` > 0  -- Exclude invalid ages\n  AND `Vict Sex` IS NOT NULL  -- Ensure victim sex is available\nGROUP BY \n  `Vict Age`, \n  `Vict Sex`\nORDER BY \n  `Vict Age` ASC, \n  `Vict Sex` ASC;\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "project": "project_id",
     "rawSql": "SELECT \r\n  FORMAT_DATE('%A', `Date Occ`) AS day_of_week,\r\n  COUNT(*) AS occurrence_count\r\nFROM \r\n  `project_id.bdeminiproject.master`\r\nGROUP BY \r\n  day_of_week\r\nORDER BY \r\n  occurrence_count ASC ;\r\n"
    }
   ]
  }
 ]
}